### ISSUE TITLE
Confused with usage

### ISSUE THREAD

**Issue by chocolatedesue** [denpadokei/Voiceroid2Sharp#3]
Only program based on the Framwork4.72 could use it. 
It fail even when I use it as dll.

How can can use it at the .Net6.0 in my program?

**Comment by chocolatedesue** [comment]
Maybe the .Net 6.0, Not Framwork.

**Comment by denpadokei** [comment]
We apologize for the inconvenience.
WPFStandardControls" is only supported by the .Netframework, so it does not work with .Net6.0.

**Comment by chocolatedesue** [comment]
Got it

Thanks for timely reply.
